# Site settings
title: Presentacion Sonic Pi
email: lagrimaescrita@gmail.com
description: >

baseurl: "https://rubentr.github.io/introduccion-sonic-pi"
url: "https://rubentr.github.io"

timezone: Europe/Madrid

markdown: kramdown
highlighter: rouge